In [ ]:
# List
angka1 = 1
angka2 = 2
angka3 = 3

# kumpulan data angka
data_angka = [1,2,3,4]
print(data_angka)

# kumpulan data string
data_string = ["joni","jono","jeni"]
print(data_string)

# kumpulan data boolean
data_boolean = [True,False,True,True]
print(data_boolean)

# kumpulan data campuran
data_mix = [1,"Cireng","John",True]
print(data_mix)

# cara alternatif membuat list
data_range = list(range(0,10))
print(data_range)

# membuat list dengan for loop, list comprehension
list_with_for = [i**2 for i in range(0,10)]
print(list_with_for)

# membuat list menggunakan for dan if
list_with_for_if = [i for i in range(0,10) if i !=5]
print(list_with_for_if)

[1, 2, 3, 4]
['joni', 'jono', 'jeni']
[True, False, True, True]
[1, 'Cireng', 'John', True]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 2, 3, 4, 6, 7, 8, 9]


In [ ]:
# akses elemen dalam list python
list1 = ['matematika','fisika','kimia', 1993]
list2 = [1,2,3,4,5,6,7]

print("list1[0]: ", list1[0])
print("list2[1:5]: ", list2[2:9])

list1[0]:  matematika
list2[1:5]:  [3, 4, 5, 6, 7]


In [ ]:
# update elemen dalam list python
list = ['matematika','fisika','kimia', 1993]
print ('elemen pada index ke-2:',list[2])

list[2] = 'biologi'
print("elemen pada index ke-2:", list[2])

elemen pada index ke-2: kimia
elemen pada index ke-2: biologi


In [ ]:
# hapus elemen dalam list python
list = ['matematika','fisika','kimia', 1993]
print(list)

del list[2]
print(list)

['matematika', 'fisika', 'kimia', 1993]
['matematika', 'fisika', 1993]


In [ ]:
# tuple

tup1 = ('honda', 'yamaha', 'suzuki', 2017)
tup2 = (1, 2, 3, 4, 5 )
tup3 = "a", "b", "c", "d"

print(tup1)
print("tup1[0]:",tup1[0])
print("tup2[1:5]:", tup2[1:5])

('honda', 'yamaha', 'suzuki', 2017)
tup1[0]: honda
tup2[1:5]: (2, 3, 4, 5)


In [ ]:
# update elemen dalam tuple
tup1 = ('ana','ani','ane')
tup2 = (1,4,3,9,4)

#tup2[1] = 2
print(tup2)


(1, 4, 3, 9, 4)


In [ ]:
# hapus elemen dalam tuple
tup = ('fisika', 'kimia', 1993, 2017)
print(tup)

#del(tup[1])

('fisika', 'kimia', 1993, 2017)


In [ ]:
# dictionary
dict = {'Nama': 'Goku', 'Umur': '22'}
print(dict['Nama'],dict['Umur'])
print(dict['Umur'],dict['Nama'])


Goku 22
22 Goku


In [ ]:
# update elemen dalam dictionary
dict = {'Nama': 'Goku', 'Umur': '22'}
dict['Umur'] = 20

print(dict)
dict['Pekerjaan'] = 'Body Guard'
print(dict)

{'Nama': 'Goku', 'Umur': 20}
{'Nama': 'Goku', 'Umur': 20, 'Pekerjaan': 'Body Guard'}


In [ ]:
# hapus elemen dalam dictionary
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}

del dict['Name'] # hapus entri dengan key 'Name'
dict.clear() # hapus semua entri di dict
del dict # hapus dictionary yang sudah ada

dict = {'Name': 'Jagoan'}
print(dict)

{'Name': 'Jagoan'}


In [ ]:
# set
my_set = {1,10,4,2,3,5,5}
print(my_set)

{1, 2, 3, 4, 5, 10}


In [26]:
# map
# variasi fungsi map

# Menerapkan Fungsi ke List
def square(x):
  return x*2

my_list = [1, 2, 3, 4]
result = map(square, my_list)  # Mengaplikasikan fungsi square ke setiap elemen dalam my_list
result_list = list(result)  # Mengonversi hasil map ke list
print(result_list)

# for x in result_list:
#   print(x)

[2, 4, 6, 8]


In [ ]:
# Menggunakan Fungsi Lambda
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x * x, numbers))

print(squared_numbers)

[1, 4, 9, 16, 25]


In [ ]:
# Menerapkan Fungsi ke Beberapa List

angka1 = [1, 2, 3]
angka2 = [4, 5, 6]
sum_angka = list(map(lambda x, y: x + y, angka1, angka2))
print(sum_angka)

[5, 7, 9]


In [ ]:
# Menggabungkan map() dengan Fungsi Bawaan
numbers = ["1", "2", "3", "4"]
print(numbers)
int_numbers = list(map(int, numbers))
print(int_numbers)

['1', '2', '3', '4']
[1, 2, 3, 4]


In [ ]:
# Menerapkan Fungsi pada List of Dictionaries

people = [
    {"nama": "Allice", "umur": 20},
    {"nama": "Bob", "umur": 25},
    {"nama": "Charlie", "umur": 17}
]

def get_nama(person):
  return person["nama"]

nama = list(map(get_nama, people))
print(nama[1])

Bob


In [ ]:
# list comprehension

# list biasa
list = []
for i in range(10):
    list.append(i)
print(list)

# list comprehension
list = [i for i in range(10)]
print(list)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# Membuat List Angka Kuadrat

list = [i*i for i in range(10)]
print(list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
# Menggunakan kondisi

list = [i*i for i in range(10) if i % 2 == 0]
print(list)

[0, 4, 16, 36, 64]


In [ ]:
# Membuat list berisi nilai yang sama (konstan)

names = ["bean" for x in range(5)]
print(names)

['bean', 'bean', 'bean', 'bean', 'bean']


In [ ]:
# Mengubah kalimat menjadi list karakter

sentence = "belajar python"
chars = [char for char in sentence]
print(chars)

['b', 'e', 'l', 'a', 'j', 'a', 'r', ' ', 'p', 'y', 't', 'h', 'o', 'n']


In [13]:
# Matriks 3x3 berisi nol
array_2d = [[0 for _ in range(3)] for _ in range(3)]
print(array_2d)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [15]:
# Matriks identitas 3x3
identity_matrix = [[1 if i == j else 0 for j in range(3)] for i in range(3)]
print(identity_matrix)

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [19]:
# membuat matriks menggunakan numpy
import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
